version: '3.8'

services:
  web:
    build: .
    platform: linux/amd64
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqldb://root:askGPT@db:3306/tutorial_db

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: askGPT
      MYSQL_DATABASE: tutorial_db
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: